import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  home: [
    { type: 'doc', label: 'Get Started', id: 'home/get-started' },
    'home/roadmap',
    {
      type: 'category',
      label: 'Basics',
      link: { type: 'doc', id: 'home/basics/basics' },
      items: [
        {
          type: 'category',
          label: 'Swap',
          link: { type: 'doc', id: 'home/basics/swap/swap' },
          items: [
            'home/basics/swap/atomic-swaps',
            'home/basics/swap/order-matching-engine',
          ],
        },
        'home/basics/stake/stake',
        'home/basics/liquidity-provision',
        {
          type: 'category',
          label: 'Token',
          link: { type: 'doc', id: 'home/basics/token/token' },
          items: ['home/basics/token/seasons'],
        },
        'home/basics/supported-chains',
        {
          type: 'category',
          label: 'Guides',
          link: { type: 'doc', id: 'home/basics/guides/guides' },
          items: [
            'home/basics/guides/btc-wbtc',
            'home/basics/guides/wbtc-btc',
            'home/basics/guides/wbtc-wbtc',
            'home/basics/guides/btc-swbtc',
            'home/basics/guides/swbtc-btc',
            'home/basics/guides/btc-dlcbtc',
            'home/basics/guides/dlcbtc-btc',
            'home/basics/guides/stake-seed',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      link: { type: 'doc', id: 'home/security/security' },
      items: ['home/security/bug-bounty'],
    },
    'home/governance',
    {
      type: 'category',
      label: 'FAQs',
      link: { type: 'doc', id: 'home/faqs/faqs' },
      items: ['home/faqs/support'],
    },
    'home/garden-brand-guide',
  ],

  developers: [
    'developers/developers',

    {
      type: 'category',
      label: 'Supported Chains',
      link: { type: 'doc', id: 'developers/supported-chains' },
      items: [],
    },
    {
      type: 'category',
      label: 'Garden API',
      link: { type: 'doc', id: 'developers/api/api' },
      items: [
        'developers/api/auth',
        'developers/api/relayer',
        'developers/api/orderbook',
      ],
    },
    {
      type: 'category',
      label: 'Garden SDK',
      link: { type: 'doc', id: 'developers/sdk/sdk' },
      items: [
        {
          type: 'category',
          label: 'React hooks (recommended)',
          link: {
            type: 'doc',
            id: 'developers/sdk/react-hooks/installation',
          },
          items: [
            'developers/sdk/react-hooks/installation',
            'developers/sdk/react-hooks/quickstart',
            'developers/sdk/react-hooks/wallet-config',
            'developers/sdk/react-hooks/usegarden-hook',
            'developers/sdk/react-hooks/swap-and-initiate',
            'developers/sdk/react-hooks/auto-redeems',
          ],
        },
        'developers/sdk/installation',
        'developers/sdk/configure-sdk',
        'developers/sdk/quote',
        'developers/sdk/swap-and-initiate',
        'developers/sdk/redeems-and-refunds',
        'developers/sdk/get-transactions',
      ],
    },

    {
      type: 'category',
      label: 'Testing in localnet',
      link: { type: 'doc', id: 'developers/merry/testing-in-localnet' },
      items: ['developers/merry/merry', 'developers/merry/merry-cmds', 'developers/merry/merry-services'],
    },
    {
      type: 'category',
      label: 'Cookbook',
      link: { type: 'doc', id: 'developers/cookbook/cookbook' },
      items: [],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
