name: Docs build and versioning

on:
  push:
    branches:
      - main

env:
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Environment Setup
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup yarn and install
        run: |
          corepack enable
          yarn set version stable
          yarn install --immutable

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Environment Setup
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Build Project
        run: yarn build
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}

  versioning-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Restore build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Get latest version
        id: get-version
        run: |
          if [ -d "versioned_docs" ]; then
            LATEST_VERSION=$(ls versioned_docs | grep -E "version-2\.0\.[0-9]+" | sort -V | tail -n 1 || echo "version-2.0.0")
            if [ "$LATEST_VERSION" = "version-2.0.0" ]; then
              NEW_VERSION="version-2.0.1"
            else
              CURRENT_NUMBER=$(echo $LATEST_VERSION | grep -oE "[0-9]+$")
              NEW_NUMBER=$((CURRENT_NUMBER + 1))
              NEW_VERSION="version-2.0.$NEW_NUMBER"
            fi
          else
            mkdir -p versioned_docs
            NEW_VERSION="version-2.0.1"
          fi
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Copy Docs to Versioned Directory
        run: |
          mkdir -p "versioned_docs/$NEW_VERSION"
          cp -r build/home "versioned_docs/$NEW_VERSION/"
          cp -r build/developers "versioned_docs/$NEW_VERSION/"

      - name: Update versions.json
        run: |
          NEW_VERSION_NUMBER="${NEW_VERSION#version-}"
          if [ -f "versions.json" ]; then
            VERSIONS=$(cat versions.json | jq ". |= [\"$NEW_VERSION_NUMBER\"] + .")
            echo "$VERSIONS" > versions.json
          else
            echo "[\"$NEW_VERSION_NUMBER\"]" > versions.json
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add versioned_docs/ versions.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: Add new version $NEW_VERSION"
            git push
          fi

  notify:
    needs: versioning-docs
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification (Stegzilla)
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Docs v2 upgrade"
          message: |
            New push detected to feat/ci-pipeline

            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Author:** ${{ github.actor }}
          colour: "#e36492"
          username: Garden docs
